### ISSUE TITLE
Allow categorical pallette for more than 8 values

### ISSUE THREAD

**Issue by schaunwheeler** [Valassis-Digital-Media/geoplotter#9]
The current categorical palette uses the Bokeh colorblind8 palette, which is very limited. Something like this could work better:

```
from bokeh.palettes import Plasma256
from numpy import unique

def colorize_numeric_list(string_list):
    unique_values, numeric_list = unique(string_list, return_indices=True)
    n_seeds = max(numeric_list) + 1
    n_skips = int(len(Plasma256) / n_seeds) * 2
    palette = Plasma256[::n_skips]
    palette = [x for y in list(zip(palette, reversed(palette))) for x in y]
    colors = [palette[j] for j in numeric_list]
    return colors
```

The interleaving from different ends of the continuous palette better ensures visual differentiation. The colorblind palette is probably still the best course for cases that involve 8 or fewer categories.

**Comment by jbednar** [comment]
You could consider using the 256-color categorical colormaps at https://colorcet.pyviz.org/user_guide/Categorical.html .  If you want to do a bit of work, you can even seed it with the colorblind8 palette, then generate the other 248 colors to be distinguishable from those, though making them also be colorblind safe would be a good bit more difficult.
